### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#10]
The aspect link seems to be broken?
https://gama-platform.github.io/wiki/Statements#aspect

**Comment by LuanaMarrocco** [comment]
I also notice that this link doesn't appear correctly. 
https://gama-platform.github.io/wiki/Statements#write

**Comment by benoitgaudou** [comment]
Hi,
This is perfectly right, but this issue is subsumed by the issue #11, relating the same issues.
Cheers

Benoit
