### ISSUE TITLE
Need new gif for front page

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama-platform.github.io#100]
**Is your request related to a problem? Please describe.**
As we're about to release a new version of GAMA, the current gif is outdated

![image](https://user-images.githubusercontent.com/16764085/166857473-7b23a3a8-722f-4c7a-9b7e-e4f6145ffb99.png)

**Describe the solution you'd like**
Make a new gif

**Comment by ptaillandier** [comment]
I began to work on a new model for the generation of the gif.
I committed it here: https://github.com/gama-platform/gama.experimental/tree/GAMA_1.8.2/GAMA%20models%20for%20new%20version

Feel free to improve it to generate the gif.

**Comment by agrignard** [comment]
here you are
https://github.com/gama-platform/gama.resources/blob/main/video_gif/GAMA_GIF.mp4.gif
