### ISSUE TITLE
Lack of information about debugging

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#101]
**Describe the bug**
As a gama developper, we sometimes need to use specific flags to set the gama settings or to give to opengl, mainly to debug. So maybe we should add a page in the `Developing Gama` to reference all those settings.

**Comment by RoiArthurB** [comment]
Trying to document every possible flags seems to be a bit too much work to maintain... However, I think it's possible to document our customs flags (mostly in the [FLAGS.java](https://github.com/gama-platform/gama/blob/GAMA_1.9.2/ummisco.gama.annotations/src/ummisco/gama/dev/utils/FLAGS.java) file), then to also point at documentation's place of important element embedded inside GAMA.

I'm thinking it could be useful to point at : 
- Eclipse / SWT flags
- JOGL flags
- else ? @AlexisDrogoul 

---

I created the wiki page to fill for this purpose here : https://github.com/gama-platform/gama/wiki/UsingGamaFlags
