### ISSUE TITLE
Empty code lines in operators special cases

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#102]
**Describe the bug**
In the documentation, some operators have empty code lines in the `special cases` section. It seems to come from the example attribute of the @doc in the java code, that is not mentioned but for some reason still generated.

**To Reproduce**
Go to [https://gama-platform.org/wiki/OperatorsSZ#saved_simulation_file](https://gama-platform.org/wiki/OperatorsSZ#saved_simulation_file)

See this:
![image](https://user-images.githubusercontent.com/6374469/166861550-e1facb32-b624-4368-8e0e-577633b109dd.png)

**Expected behavior**
No empty code line

**Comment by benoitgaudou** [comment]
Attempt to  fix with c3a8f54

**Comment by lesquoyb** [comment]
working !
