### ISSUE TITLE
Dynamic linking to source code in the wiki and the website

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#106]
**Is your request related to a problem? Please describe.**
To make the documentation process easier it would be great to write the link to a gaml model in the wiki and to have the possibility to display the content of the file in a read only mode in the wiki and in the website.

Typically here for instance
https://github.com/gama-platform/gama/wiki/ThreeD_step1#complete-model

There is a link to the source model + a rewriting of the code below which is very redundant and any modification in the source is not guaranted to be done in the wiki (unless someone do it)

**Comment by RoiArthurB** [comment]
The compiled website will display like this : 
![image](https://user-images.githubusercontent.com/16764085/167293249-43d80a97-b372-421f-b879-eeb397a67d2f.png)

To do so, you should write a code block with the language name followed by the keyword `reference` and the linked page as code block. See exemple : 

```md
```gaml reference
https://github.com/gama-platform/gama/blob/GAMA_1.8.2/msi.gama.models/models/Tutorials/Predator%20Prey/models/Model%2001.gaml
```                                                                     .
```

cf. plugin documentation there : https://github.com/saucelabs/docusaurus-theme-github-codeblock
