### ISSUE TITLE
Add a changelog from 1.8.1 to 1.9.1

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#110]
I already created a [page](https://github.com/gama-platform/gama/wiki/Changelog) based on the draft we did in the coding camp, but I'm not involved enough in most of the points to really talk about them. 
Also there are probably some points missing so feel free to complete it

**Comment by lesquoyb** [comment]
Trying to close this one, @chapuisk, @benoitgaudou  and @AlexisDrogoul could you write a few words on the parts you know well and that are empty/only notes (for example `Parameters exploration methods` , `Serialization`, ` Experiment reproducibility` etc.) ?
If you could also take a few minute to read the parts that are already written just to check that everything is correct

**Comment by lesquoyb** [comment]
Pages to fix:

- Detailed [page](https://github.com/gama-platform/gama/wiki/Changelog)
 - also small summary in the github release description

**Comment by RoiArthurB** [comment]
Changelog page has been filled, GitHub Release post too, and a short summary will be soon pushed on the Download page of the website
