### ISSUE TITLE
The "lower than" signs in code are not rendered correctly

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#114]
**Describe the bug**
The `<` signs in gaml example codes are often replaced with the text `&lt;` and not interpreted as a symbol.
For example [here](https://gama-platform.org/wiki/OperatorsBC#contains) where we can read `container&lt;KeyType,ValueType> contains unknown ---> bool` instead of `container<KeyType,ValueType> contains unknown ---> bool`

**Comment by RoiArthurB** [comment]
I let you fix the python script, and I'll apply it on the website.

As we saw together, it's not necessary to escape signs (to break HTML-like tags) of text rendered as code (so between `` in line or ``` in block) :)
