### ISSUE TITLE
https://github.com/gama-platform/gama/wiki/Headless

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama-platform.github.io#115]

**Comment by sriramab** [comment]
Link is empty. Probably linked incorrectly ?

**Comment by RoiArthurB** [comment]
Yes, it has been renamed to RunningHeadless (more coherent with RunningExperiment and others).

But you're not supposed to follow this list anymore, it's missing new pages or have removed pages. I'll advise you to follow pages available on the wiki sidebar directly if you want to improve the wiki :)
