### ISSUE TITLE
Search engine results order could be improved

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#116]
**Is your request related to a problem? Please describe.**
I'm often looking for the description of operators/statements using the search engine, but the order of the results shown makes it harder than it should be

example here looking for the chart statement:
![image](https://user-images.githubusercontent.com/6374469/174525161-9d76070e-c9b2-491f-ae88-d650f3d427d3.png)
I have to scroll down all the tutorials that use charts to find the page for that statement, and even when precising `chart statement` it only is the 5th choice and once on that page I have to find `chart` and click on it in the list of all the statements to finally access it's description
![image](https://user-images.githubusercontent.com/6374469/174525619-682f05be-ee2e-47a5-8e89-2e05e6a81182.png)
![image](https://user-images.githubusercontent.com/6374469/174525688-d1ffee5a-5d42-486c-a8bc-e99cea4f19b2.png)
![image](https://user-images.githubusercontent.com/6374469/174525754-0d087060-127f-4692-9431-63e1b1f9aae4.png)

**Describe the solution you'd like**
Having operators and statements with a higher priority than most of the pages (especially the blog and events pages) so it comes out on top of the search results

**Comment by RoiArthurB** [comment]
Some improvement have been made
![image](https://user-images.githubusercontent.com/16764085/185343730-fc4327ca-494e-44b0-b450-e35f7829af0b.png)

Feel free to reopen if still relevant :)
