### ISSUE TITLE
Horizontal lines are inconsistent in BuiltInSkills page

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#117]
**Describe the bug**
In the [built in skills page](https://gama-platform.org/wiki/BuiltInSkills), there are horizontal lines used to separate different parts of the page, but I can't find the logic behind it and it makes the reading a lot more difficult.
For example with [that skill](https://gama-platform.org/wiki/BuiltInSkills#has_more_message), we have a horizontal line separating the name of the action and its return type, while for the action [join_group](https://gama-platform.org/wiki/BuiltInSkills#join_group) there is no horizontal line at all (not even to separate the action from the others.

Edit:
Some precisions:
* this problem seems to appear in other pages
* I feel like it's related to the content of the action being empty

**Comment by RoiArthurB** [comment]
@benoitgaudou any idea ? :)

**Comment by benoitgaudou** [comment]
Basically a double reason for these horizontal lines:
* `****` is interpreted as an horizontal line
* When an action does not have any documentation, `****` is added after the name of the action.

So I've updated the documentation of some actions.

One remaining point: what is this action (in ThreadSkill.java) ?:

```
	@action (
			name = "runnable_action"
			)
	public Object primExternalFactorOnRemainingTime(final IScope scope) throws GamaRuntimeException {
		return null;
	}
```

I do not know how to document it :-)

**Comment by lesquoyb** [comment]
Maybe @ptaillandier knows about it ?

**Comment by ptaillandier** [comment]
It is a new (very useful) skill  that allows to run an action in a separate
thread.
In the new version (I developed the first version, and Alexis improved it
after), the action "runnable_action" does not exist anymore.

**Comment by benoitgaudou** [comment]
Hi @ptaillandier,
In the current git version of GAMA (GAMA_1_8_2 branch), the action still exists (just pull a few minutes ago).
Method : primExternalFactorOnRemainingTime

Benoit

**Comment by AlexisDrogoul** [comment]
It is usually a problem of refresh -- you can try to remove the gama folder, clore the `core` project, and reopen it...

**Comment by benoitgaudou** [comment]
Looking at the GitHub web interface, for the file ThreadSkill,
https://github.com/gama-platform/gama/blob/GAMA_1.8.2/msi.gama.core/src/msi/gaml/skills/ThreadSkill.java
the method is still there (lines 141 - 146)

**Comment by AlexisDrogoul** [comment]
Ah yes, of course. I thought you had a problem with the name of the action. I will add some documentation to it.

**Comment by benoitgaudou** [comment]
Thks !
I just launched the documentation generation, the wiki page seems OK.
@lesquoyb I let you close the issue if it is OK for you.
