### ISSUE TITLE
Certain types are not displayed correctly in BuiltInSpecies and BuiltInSkills

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#119]
**Describe the bug**
In the description of certain variables or methods, the types are not displayed as a name (like "bool" for variables of type boolean) but by there integer value.
For example, for the attribute `host` of an agent, the documentation displays the value `29` (instead of `agent` probably) [https://gama-platform.org/wiki/next/BuiltInSpecies#agent](https://gama-platform.org/wiki/next/BuiltInSpecies#agent).
Another example would be the `linked_road` variable of an agent with the skill `skill_road` [https://gama-platform.org/wiki/BuiltInSkills#variables-8](https://gama-platform.org/wiki/BuiltInSkills#variables-8) which displays `199`.
Last example: [https://gama-platform.org/wiki/next/BuiltInSpecies#variables-3](https://gama-platform.org/wiki/next/BuiltInSpecies#variables-3) with the attribute simulation

Edit:
Other examples:
  * [https://gama-platform.org/wiki/next/BuiltInSkills#actions-3](https://gama-platform.org/wiki/next/BuiltInSkills#actions-3) the `message`type is replaced by `24` in every action
  * still in the fipa actions, the return type is `msi.gaml.extensions.fipa.FIPAMessage` for `send` and `start_conversation`
  * in [https://gama-platform.org/wiki/next/Statements#diffuse](https://gama-platform.org/wiki/next/Statements#diffuse) in the `on` statement description, the type `field` is  replaced with 31

**Comment by benoitgaudou** [comment]
I had a look at the wiki and seems that every point has been fixed.
Nevertheless, it seems that the website has not been generated ....

**Comment by lesquoyb** [comment]
Fixed thanks @benoitgaudou and @RoiArthurB
