### ISSUE TITLE
Doc : improve the presentation of multi simulation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#126]
**Describe the improvement you'd like**
The way to manipulate experiments, in particular how to display information on the same graph needs to be improved, in particular in the page : https://gama-platform.org/wiki/RunSeveralSimulations

Add a mention to permanent in this page.

**Comment by lesquoyb** [comment]
I also updated the [batch documentation page](https://gama-platform.org/wiki/next/BatchExperiments#permanent) about permanent, not sure it's the best example but still better than before I think

**Comment by lesquoyb** [comment]
Closing it, feel free to reopen if there's something missing/wrong
