### ISSUE TITLE
Not possible to use search tool with latest Safari 15.6.1

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama-platform.github.io#127]
**Describe the bug**
The search tool does not pop up anything when using Safari 15.6.1 (up-to-date). With the same machin and google chrome everything is ok !

**To Reproduce**
1. Go to Gamaplatform with Safari
2. Click on search tool

**Expected behavior**
Be able to do research on the website using Safari

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - PC Model: MacBook Pro M1

**Comment by RoiArthurB** [comment]
Update on this : 

- As GAMA's embedded web browser use WebKit, this issue is also present inside the IDE
- The new update of Docusaurus (2.3.0) didn't fix the problem
  - Surprisingly no one else than us have this issue... 🤔

**Comment by sriramab** [comment]
I was about to report this. It is also a problem on windows11 for gama 1.9

**Comment by RoiArthurB** [comment]
I finally tracked down this issue, it comes from an error in the [prism-gaml](https://github.com/RoiArthurB/prism-gaml) plugin. I'm working on it rn :)

**Comment by RoiArthurB** [comment]
Issue fixed in GAMA and GnomeWeb (two browsers using WebKit -like Safari-) : 
![image](https://user-images.githubusercontent.com/16764085/219587002-1c74cbcf-cde0-4c2a-8242-8c0370392fad.png)

Feel free to re-open if the issue persists for any of you 🤗
