### ISSUE TITLE
Add documentation for docker deployment of gama-server 

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#128]
**Is your request related to a problem? Please describe.**
There is currently no documentation at all about how to package gama in a docker container. While it makes little sense for gama with a gui, some users could highly benefit from running gama-server from a docker image 

**Describe the solution you'd like**
Either add a section in the gama-headless page of the documentacion, or create a new page specific to docker

**Comment by RoiArthurB** [comment]
Done here gama-platform/gama.wiki:061c3b2a https://gama-platform.org/wiki/next/HeadlessServer
