### ISSUE TITLE
Remove the background animation

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#133]
**Is your request related to a problem? Please describe.**
The background animation of the 1st page makes the site become a bit sluggish and slow on some browsers. Plus, it impacts the readability of the whole and it not really nice on a white background.

**Describe the solution you'd like**
I would like it to be simply removed.

**Comment by RoiArthurB** [comment]
@AlexisDrogoul @agrignard What do you think about this redesign ? :)

| | Old website | New website |
|---|---|---|
| Light | ![image](https://user-images.githubusercontent.com/16764085/216232172-34c7264a-ec1e-47a0-9078-a5890e61215e.png) | ![image](https://user-images.githubusercontent.com/16764085/216232217-4fba2a10-da00-49cc-b566-79bd5f9d127b.png) |
| Dark | ![image](https://user-images.githubusercontent.com/16764085/216232141-8eeb946a-8b96-4137-a665-40e6219971da.png) | ![image](https://user-images.githubusercontent.com/16764085/216232019-f9563197-3e57-43c8-9ab4-8474e0a8d45f.png) |

**Comment by agrignard** [comment]
I found it more way readable like this. So overall it's a big yes on my side.

One comment:
For the blue banner announcing the GAMA Days 2022... why not even if it's maybe to much in the middle of the page (what about placing it in the bottom? (less visible but do we really want this in the middle of the website?) also the video is about Gama Days 2021 not 2022

**Comment by RoiArthurB** [comment]
@agrignard 

> For the blue banner announcing the GAMA Days 2022... why not even if it's maybe to much in the middle of the page (what about placing it in the bottom?

I just follow the most classical layout for software/project's front page, and it's very commun to put there the latest big event relative to this project (a new major release, event, else); so I think it's appropriate to have a display to the GAMA Days for new comers seeing that (1) the project is active, (2) have an active community and (3) can give a good overview of what is GAMA

> also the video is about Gama Days 2021 not 2022

I know, I'm currently gathering every videos to make the yt playlist, and I'll update the link at that time (even if it's not the good year, it still relevant for my 3 points above) :)
