### ISSUE TITLE
Documentation for pair datatype

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama-platform.github.io#135]
**Describe the bug**
The documentation for the pair in the editor seems to be incorrect. Also, I can't change the value of the key or value attribute of a pair although it wasn't said to be read-only in the documentation.

**Screenshots**
![5](https://user-images.githubusercontent.com/62107278/220820561-23605599-6d6d-4448-86bb-4dc39bd78087.png)

**Comment by lesquoyb** [comment]
also the documentation for the [pair type](https://gama-platform.org/wiki/next/DataTypes#pair) says that key and values are of type string, which is wrong

**Comment by benoitgaudou** [comment]
The screenshot is in fact the documentation of the definition of a new local variable (formerly using the statement let statement), it is not the documentation of the pair.

I also update the documentation of the pair type, specifying that the 2 fields are read-only.
