### ISSUE TITLE
Missing documentation for possible use of to_rectangles and similar function

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama-platform.github.io#136]
**Describe**
Missing possible use of `to_rectangles (geometry, point)` returns a list of geometry with some non-rectangle shape by intersecting with the input geometry, different from
`to_rectangles (geometry, point, true)`
`to_rectangles (geometry, point, false)`
in the documentation, which return a list of only rectangles.

**Comment by lesquoyb** [comment]
Closing as duplicated (#129)
