### ISSUE TITLE
Improve file paths' documentation

### ISSUE THREAD

**Issue by ScriBanana** [gama-platform/gama-platform.github.io#137]
Hi,

**Describe the bug**
Importing a GAML file with an experiment makes it so you can run it from the both its definition and importing file. (Example : If I define an experiment "Run" in `Experiment.gaml` and use `import "Experiment.gaml"` in another file, I will have the ![image](https://user-images.githubusercontent.com/72523821/220095850-169bd23c-57a3-465b-aca7-ffee0d4ce803.png) button over both in the UI.)
The issue is that any relative path called in the model will depend on the file the button is pressed from.

**To Reproduce**
Build a file system like this :
```
├── Models
│   ├── Experiments
│   │   └── Experiment.gaml
│   └── Main.gaml
└── Utilities
    └── GenerateExportFiles.gaml
```
with `main.gaml` :
```java
model Main
import "../Utilities/GenerateExportFiles.gaml"
import "Experiments/Experiments.gaml"
```
`Experiment.gaml` :
```java
model Experiments
import "../Main.gaml"
experiment run;
```
`GenerateExportFiles.gaml` :
```java
model GenerateExportFiles
global {
	string outputDirectory <- "../OutputFiles/";
	init {
		save "I am data!" to: outputDirectory + "Data.csv" type: csv rewrite: true;
	}
}
```

Here's the result after running the experiment both from `Main.gaml` and  `Experiment.gaml` :
```zsh
├── models
│   ├── Experiments
│   │   └── Experiments.gaml
│   ├── Main.gaml
│   └── OutputFiles
│       └── Data.csv
├── OutputFiles
│   └── Data.csv
└── Utilities
    └── GenerateExportFiles.gaml
```

**Expected behavior**
The `OutputFiles` directory being only created at the root of the project, at the location the path relative to where the `save` function was called from :
```zsh
├── models
│   ├── Experiments
│   │   └── Experiments.gaml
│   └── Main.gaml
├── OutputFiles
│   └── Data.csv
└── Utilities
    └── GenerateExportFiles.gaml
```

**Desktop (please complete the following information):**
- OS: Manjaro Linux x86_64
- GAMA version: 1.8.2 RC2

I could simply not cross-import gaml files as a workaround, but it still looks like an issue.

**Comment by RoiArthurB** [comment]
Hi @ScriBanana 

Sorry for the delayed answered (didn't saw the notification on this issue). Actually the documentation already explained this behavior here : https://gama-platform.org/wiki/ModelOrganization

But I agree that this little part is a bit difficult to spot. I'll add a part title so it can be catched by the search engine as well as a reminder at the location you pointed (as I guess you're a new comer with this software, I'll follow your logic for finding informations ;) )

I'll just ping @lesquoyb to know if you have some other enhancement idea about this point on the documentation :)

**Comment by lesquoyb** [comment]
Not sure about the documentation, but it could be nice to have a few statements to get the current file's path, the experiment file's path, directories and maybe others, so users can compose paths relative to what they think makes more sense. Like:
```
string embedded_file_path <- current_file_directory + "../includes/framework_file.png";
string custom_file_path <- experiment_file_directory + "../includes/my_file,png"
```

**Comment by ScriBanana** [comment]
Hi @RoiArthurB, hi all,

Thanks, although I am very unsure that the documentation makes things clear enough as of yet, to be honest.

Let me reformulate what I understood :
- Statements are defined in the order they are read, i.e. in which they are imported. (The page you linked earlier)
- The order of definition of models depend not on where the called experiment is defined, but on which file it is called from, using the green button.
- Relative path in a statement will depend not on the file it is defined in, but on where the model is run from (i.e. where you pressed the green button from). So if `main.gaml` imports `experiments.gaml` and I press the button of an experiment defined in the former, all relative paths defined in variables will refer to `main.gaml`, regardless of where they are defined.
- However, relative path in an `import` statement will always relate to the current file location. In my example tree above, if I `import "../Utilities/GenerateExportFiles.gaml"` in `main.gaml`, this will always lead to the file, regardless on if I pressed the button in `main.gaml` or `experiments.gaml`.

So two things I failed to understand, that had me confused :
- The discrepancy between the last two statements. I am used to inputting relative path in `import` statements, which never change and always start from the importing file itself. Now, when I use a relative path inside a statement in a model definition (in a variable) the behaviour changed seemingly unexpectedly and now the path is relative to the caller file.
- The order in which files are imported depends on where the button is pressed from, not on where the experiment is defined, which is a bit confusing (could be mentioned [here](https://gama-platform.org/wiki/next/LaunchingExperiments#from-an-editor), for example).

So yes, maybe a section dedicated to what happens in what order when an execution is launched would make things clearer. Possibly as a complement to https://gama-platform.org/wiki/next/RuntimeConcepts ?

**Comment by RoiArthurB** [comment]
A short explanation of this behavior has been added on the page https://github.com/gama-platform/gama/wiki/ModelOrganization as a note while describing how to import files, as well as in https://github.com/gama-platform/gama/wiki/DefiningExportFiles as a reminder while saving data with relative paths.

> So yes, maybe a section dedicated to what happens in what order when an execution is launched would make things clearer. Possibly as a complement to https://gama-platform.org/wiki/next/RuntimeConcepts ?

I would disagree to add this point on this page as it's an overview of the main steps for creating a simulation and the scheduling of agents inside. I'm not sure that it's relevant to add information about how path are processed while exporting data there.

---

Considering this issue closed now, feel free to reopen if you consider some other places might be relevant :)
