### ISSUE TITLE
Missing file for the link

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama-platform.github.io#140]
Open the page: https://gama-platform.org/wiki/Pedagogical-Materials
##1. The MementoAlgoGAMLv1.9.0.pdf  is missing 
In the Memo GAML page (https://gama-platform.org/wiki/Pedagogical-Materials) the file PDF is missing for the link.
"A summary of the organization of a GAML model, its main parts, and the main keywords, statements: **[PDF](https://gama-platform.org/resources/other/PedagogicalMaterial/1.9.0/MementoAlgoGAMLv1.9.0.pdf)**."
https://gama-platform.org/resources/other/PedagogicalMaterial/1.9.0/MementoAlgoGAMLv1.9.0.pdf
##2. PedagogicalMaterials are missing 
The links to PDF files and models in the page are broken.

![image](https://user-images.githubusercontent.com/11825516/231431172-a45ab07e-052d-42e7-b9bc-9f5419eba6bf.png)
![image](https://user-images.githubusercontent.com/11825516/231433651-18a929ff-7456-4423-aad0-4f9f5d87ad22.png)
![image](https://user-images.githubusercontent.com/11825516/231434219-f4bd8760-9a9b-41d9-b2ec-c059b8b22d2f.png)

**Comment by benoitgaudou** [comment]
All the files have been committed
