### ISSUE TITLE
Prepare texts for advertising 1.9

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#142]
Facebook, youtube channel, twitter, website, mailing list, ctu website

scientific mailing list:
- simsoc
- commod
- agents
- espacedev
- ird/cnrs

preparing an image

make sure that the website thumbnail/preview image is still up to date

**Comment by agrignard** [comment]
Also the text of the group list is outdated https://groups.google.com/g/gama-platform

**Comment by AlexisDrogoul** [comment]
First point, ok to send to these groups/lists, but what do we send ? Is there somewhere a shared doc / page where we can agree on a given text (in French, English, maybe Vietnamese @hqnghi88 ?) + the corresponding illustrations + the link ? If not, I propose this document : https://docs.google.com/document/d/1f34XZtVFGMEBobzyN96eAlo3IhEPSHusw7c5njwPo24/edit

Feel free to edit it at will, add, remove things ... 

Second point, we need to clearly establish the responsibilities for each. I propose these below (please comment/edit or tick when done).

Social Media 
- [ ] Facebook (in English): @benoitgaudou for the official page
- [ ] LinkedIn (in English): @AlexisDrogoul for the official page
- [ ] Twitter ? @sriramab 
- [ ] TikTok ? 
- [ ] Instagram ? 
- [ ] Others ? (please add) @gama-platform/core 

Institutions 
- [ ] IRD newsletter in France and Vietnam (French and English): @AlexisDrogoul 
- [ ] INRAE newsletter / site (French) : @ptaillandier 
- [ ] CNRS with respect to their "labelisation" of GAMA (French): @benoitgaudou 
- [ ] CTU newsletter (English and/or Vietnamese): @hqnghi88 
- [ ] Others ? (please add) @gama-platform/core 

Laboratories
- [ ] UMMISCO (in French): @AlexisDrogoul 
- [ ] ACROSS (in English): @lesquoyb 
- [ ] Espace Dev (in French): @chapuisk 
- [ ] MIAT (in French): @ptaillandier 
- [ ] IRIT (in French): @benoitgaudou 
- [ ] Others ? (please add) @gama-platform/core 

Mailing Lists

- [ ] GAMA users: @lesquoyb 
- [ ] SimSoc: @AlexisDrogoul 
- [ ] ComMod: @AlexisDrogoul 
- [ ] JFSMA ? @ptaillandier 
- [ ] Others ? (please add) @gama-platform/core
