### ISSUE TITLE
Better way to acces to the newsgroup

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#143]
**Is your request related to a problem? Please describe.**
On the wlecome page open from GAMA it's easy to access to the google newsgroup https://groups.google.com/g/gama-platform
<img width="704" alt="Screenshot 2023-04-14 at 11 06 20" src="https://user-images.githubusercontent.com/3928502/231939176-21ab0dbe-71a7-41d8-ab6b-b704ec767fec.png">

but hard (or hidden) from the website?

<img width="1509" alt="Screenshot 2023-04-14 at 11 06 04" src="https://user-images.githubusercontent.com/3928502/231939147-5afe3f7e-de0a-4d44-b4b7-e7806f600d04.png">

**Describe the solution you'd like**
A way to acces it easily form the land page of the website

**Comment by sriramab** [comment]
It should perhaps even be corrected to "user group" or "user forum" instead of - news group

**Comment by RoiArthurB** [comment]
Merging this issue with #164
