### ISSUE TITLE
Document how to use preferences (as a flag to gama or global or directly in the model)

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#145]
https://gama-platform.org/wiki/next/Preferences

**Comment by RoiArthurB** [comment]
@chapuisk didn't you worked on this ? If so, where did you pushed all of this documentation ? :) 

The preferences linked page didn't been updated since 2022 :/

**Comment by chapuisk** [comment]
Hey @RoiArthurB we remove this from the change log which is already quite extended. However, I can have a look to the page to update it to include the 3 methods to change preferences

**Comment by agrignard** [comment]
If I am not wrong this task has been done by @chapuisk ? https://gama-platform.org/wiki/next/Preferences

Can we consider this one as closed?

**Comment by lesquoyb** [comment]
Well I don't know, do you consider there's still work to be done on this page @chapuisk ?

**Comment by chapuisk** [comment]
Yes there is still work on the page, none of the pref have been updated. But I did a paragraph about use of preferences as tags, what the issue was refering to...

**Comment by lesquoyb** [comment]
ok then the issue is closed, I'll open a new one for updating this page
