### ISSUE TITLE
make a video trailer for the version 1.9.1

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#150]
everybody makes 10s videos of models

**Comment by agrignard** [comment]
A beta version is here:
https://youtu.be/vr42lliNzlk

Some change will be made like credits at the end
Music and Gama Credits
<img width="611" alt="Screenshot 2023-04-22 at 08 01 34" src="https://user-images.githubusercontent.com/3928502/233765791-7ee5eeeb-b53e-4b78-8141-f03f3a9b171c.png">
<img width="555" alt="Screenshot 2023-04-22 at 08 01 50" src="https://user-images.githubusercontent.com/3928502/233765792-48fab4ae-af78-4c36-93bd-883a205f4c8d.png">

**Comment by agrignard** [comment]
The last version that is currently the final one can be found here
https://youtu.be/ZGSfAuhDbsU

We can consider this issue has done.
