### ISSUE TITLE
Add a direct link to the ChangeLog from the download page

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#153]
It would be important that the ChangeLog page from the wiki is directly accessible from a button / link from the download page (something like "What's new ?" or "Changes" -- if possible a bit prominent)

**Comment by RoiArthurB** [comment]
![image](https://user-images.githubusercontent.com/16764085/232725867-2d746f40-8ddf-4924-b7b6-9a3d8403e97e.png)

Done and ready for the new website (when officially releasing 1.9.1)
