### ISSUE TITLE
Missing picture

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#156]
**Exact broken link**

In the page `https://github.com/gama-platform/gama/wiki/Troubleshooting`, in the section `Charting problems`, there is a missing picture acceeded with the link: `https://github.com/gama-platform/gama-platform.github.io/blob/master/resources/images/charts/display_when_modeling.png`

**Comment by RoiArthurB** [comment]
Can't fix, this image doesn't exist in the organization... Then I'd just removed the image 🤷🤷🤷
