### ISSUE TITLE
Agent movement broken link

### ISSUE THREAD

**Issue by guadalupebabio** [gama-platform/gama-platform.github.io#16]
In https://gama-platform.github.io/wiki/Agent-movement.html this link is broken for all the sections in that page such as https://gama-platform.github.io/wiki/references#AgentmovementFollowPath

However, it works in the wiki of the game-platform  https://github.com/gama-platform/gama/wiki/Agent-movement

**Comment by agrignard** [comment]
Hi @guadalupebabio 

Thank you for reporting this issue. 

You're right the link are broken in the github.io. Even if the link are working in the gama-platform they however redirect to a wrong page related to references (https://github.com/gama-platform/gama/wiki/references#AgentmovementFollowPath)

We will do our best to fix this issue asap

You can also have a look at this page for more information about the moving skills
https://github.com/gama-platform/gama/wiki/AttachingSkills#the-moving-skill
