### ISSUE TITLE
Add 1.9.1 to the versions of gama page

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#162]
the page is lacking a description of gama 1.9.1 [https://gama-platform.org/wiki/next/OlderVersions](https://gama-platform.org/wiki/next/OlderVersions)

**Comment by RoiArthurB** [comment]
Done :) 
![image](https://user-images.githubusercontent.com/16764085/234173788-b5de68c1-c123-4c92-9d71-2d00afa3535e.png)
