### ISSUE TITLE
Create a new section regrouping Resources from users and Projects using gama

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#164]
Move those two sections from documentation to a separate part of the website (called community or resources). 
Add a small home page with links to user groups and such

**Comment by RoiArthurB** [comment]
Half done by introducing a new section `Community` in the documentation

![image](https://user-images.githubusercontent.com/16764085/234211628-7752af12-274d-450e-b596-eb44620dd925.png)

Needs to be filled and re-organised

**Comment by lesquoyb** [comment]
I created a base home page for community based on the old Contribute page and started reorganizing the sidebar
