### ISSUE TITLE
"What's new"  wrong link

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#167]
**Describe the bug**
The what's new button in the download section is not pointing to the right change log (it's pointing to 1.9.0 it should point to 1.9.1)

<img width="1425" alt="Screenshot 2023-04-25 at 11 19 53" src="https://user-images.githubusercontent.com/3928502/234232992-7b6743bb-0710-4358-a75e-f7df9fbeccf1.png">

**Comment by lesquoyb** [comment]
actually not, it's pointing to the current changelog, and current version is 1.9.0, you can switch to 1.9.1 with the version menu

**Comment by agrignard** [comment]
It should point to 1.9.1 isn't it?

**Comment by lesquoyb** [comment]
You are right it seems hardcoded
