### ISSUE TITLE
ShapeFiles not included in the Road Traffic tutorial 

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama-platform.github.io#17]
The SapeFiles _building.shp_, _road.shp_ and _bounds.shp_ are needed to start the Road Traffic tutorial, but they are impossible to find on the website.
https://gama-platform.github.io/wiki/RoadTrafficModel_step1

**Comment by ptaillandier** [comment]
You are right: even if the shapefiles are given with GAMA (Library models -> Tutorials -> Road Traffic), we should give the possibility to directly download them from the website.

**Comment by RoiArthurB** [comment]
I've modified the wiki, I will close this issue when the website will be regenerated :)
I've simply added your answer and a link on the github folder with all the included files for this tutorial.

**Comment by RoiArthurB** [comment]
The update is online :)
