### ISSUE TITLE
Add a comment section on documentation

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#171]
**Is your request related to a problem? Please describe.**
Following a recent discussion with @RoiArthurB, we realised that comment section on a language's documentation is a big plus for users.
@sriramab also recently reported to me that there's a github widget that enables the integration of github discussions in our webpages, maybe we can use it to add a comment section easily to the website ? The tutorial is [here](https://www.freecodecamp.org/news/github-discussions-as-chat-system/)

**Comment by lesquoyb** [comment]
Any thoughts on the matter @agrignard @AlexisDrogoul @benoitgaudou @sriramab ?

**Comment by AlexisDrogoul** [comment]
I agree !

**Comment by RoiArthurB** [comment]
Done with [80eaec9ef](https://giscus.app/) adding comments for wiki pages and blog posts. I used the Giscus techno and it'll use this repo's discussion tab to host comments.
