### ISSUE TITLE
What to do with the next version's changelog

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama-platform.github.io#173]
## Problem

Currently, in the gama-platform/gama/wiki we do have 2 changelog file : One dedicated to the release from 1.8.1 to 1.9.1 and one from 1.9.1 to 1.9.2

![image](https://github.com/gama-platform/gama-platform.github.io/assets/16764085/fb95adc4-419f-4658-9b20-6519985fc795)

For the next release of GAMA, it would make sense to have only a single changelog file listed on the website. But the next release 1.9.2 isn't bringing a lot of new features (mostly bug fixes) and all the feature listing from 1.9.1 could still be relevant.

## Proposed solution

I propose to merge both changelog for the next release. 

The idea would be to just add the short changelog from 1.9.1 to 1.9.2 above the main release one, in a single page called "What's new". It would look something like this : 

```
# Major changes from 1.9.1 to 1.9.2

The GAMA development team is pleased to announce the release of GAMA 1.9.2. This is a maintenance release, aiming at fixing bugs observed in 1.9.1 and clarifying some of its concepts. No new features have been added, except the possibility to define #mouse_drag events.
Detailed changes.

## This release of GAMA contains new features and fixes, including:

[...]

# Major changes from 1.8.1 to 1.9.1

The GAMA development team is pleased to announce the release of GAMA 1.9.1

[...]
```

**Comment by lesquoyb** [comment]
I just completed a first pass of adding all the fixes and improvements of this version into [this page](https://github.com/gama-platform/gama/wiki/Changelog192), and there's actually already a good amount of content.
So maybe we can have a proper page for 1.9.2 and just link to the previous one ?

**Comment by RoiArthurB** [comment]
All merged in a single changelog file here : https://github.com/gama-platform/gama/wiki/Changelog :)
