### ISSUE TITLE
This link crashes: https://gama-platform.org/wiki/PredatorPrey_step1

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#176]
**Exact broken link**

https://gama-platform.org/wiki/PredatorPrey_step1

**To Reproduce**
The page where there is a broken link is the one on Tutorials.

**Desktop (please complete the following information):**
 - Device: MBP
 - OS: macOS
 - Browser Safari
 - Version 16.4

**Additional context**

![1  Basic Model | GAMA Platform 2023-06-01 14-33-41](https://github.com/gama-platform/gama-platform.github.io/assets/579256/3687d8c3-3cc7-4a94-a58e-be3a27020eed)

**Comment by RoiArthurB** [comment]
@AlexisDrogoul It should be fixed. The website has been fully rebuilt and published on Github Pages; could you check if the issue remains on your side please ? :)
