### ISSUE TITLE
Sidebar can't be scrolled independently 

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#178]
**Describe the bug**
In some cases the content of the sidebar can be very long and exceed the height of the page:
![image](https://github.com/gama-platform/gama-platform.github.io/assets/6374469/96b0f318-2d21-439a-8e8a-eb46271a3f4b)
The problem is that the sidebar doesn't have its own scroll and depends on the main page scrolling, so you have to scroll all the way down the page you are currently reading (which can be very long) to be able to read the next element in the sidebar

**To Reproduce**
1. Go to the documentation tab of the website
2. unfold recipes
4. See that you have to scroll all the way down the home page to see all the recipes

**Expected behavior**
it's possible to scroll the sidebar independently

**Comment by RoiArthurB** [comment]
Can't reproduce nor on Chromium based nor on Firefox... :/

So probably a bug specific to your system in conflict with Docusaurus which I won't be able to fix anyway, sorry

**Comment by lesquoyb** [comment]
Definitely something specific to the gama website as docusaurus works as expected for me. I also tried with another computer on windows 11 + edge and it has the same problem.
Thus it may be related to windows 11
