### ISSUE TITLE
Complete training session page

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#187]
**Is your request related to a problem? Please describe.**

I recently noticed that the training session page was not up to date (latest record being 2021). So I updated it with the information I had, but not sure it's complete. Can you have a look ?
[https://github.com/gama-platform/gama/wiki/TrainingSession](https://github.com/gama-platform/gama/wiki/TrainingSession)

**Comment by RoiArthurB** [comment]
Quick though : I'm not convinced this page is useful for anyone, and I'm proposing to remove it from the website
