### ISSUE TITLE
Iterator operator's page missing

### ISSUE THREAD

**Issue by LucasGrjs** [gama-platform/gama-platform.github.io#188]
**Broken link**

https://gama-platform.org/wiki/Operators#Iterator-operators

**To Reproduce**
1. Go to 'https://gama-platform.org/wiki/PseudoVariables#each'
2. Click on '[iterators](https://gama-platform.org/wiki/next/Operators#Iterator-operators)'
3. See error

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [117.0]

**Additional context**
There should be a documentation page on iterators operators at that link

**Comment by RoiArthurB** [comment]
Already fixed in the next version of the documentation about to be frozen : https://gama-platform.org/wiki/next/PseudoVariables#each leading to https://gama-platform.org/wiki/next/OperatorsSZ#Iterator-operators :)
