### ISSUE TITLE
typo on Using-BEN-simple-bdi

### ISSUE THREAD

**Issue by djradon** [gama-platform/gama-platform.github.io#192]
**Describe the bug**
In the sentence "With this definition, a social relation is not necessarily symmetric, which means Ri,j(L,D,S,F,T) is not equal by definition to Ri,j(L,D,S,F,T)", the second social relation should be Rj.i

**Comment by djradon** [comment]
URL is https://github.com/gama-platform/gama/wiki/Using-BEN-simple-bdi

**Comment by RoiArthurB** [comment]
Thanks for this correction, it's been fixed for documentation on 1.9.2 and future 1.9.3 :)
