### ISSUE TITLE
Facets of statements are not indexed 

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#193]
**Describe the bug**
When looking for `keep_simulations:` (see https://github.com/gama-platform/gama/issues/3893), I was unable to find it on the website, and it turns out that individual facets are not indexed, while (in my opinion) they should be. 

**To Reproduce**
Go to the website, type the name of one facet. 

**Expected behavior**
That, like in GAMA in the top-right search, facets are listed.

**Comment by RoiArthurB** [comment]
Fixed, I updated the Algolia's crawler script to gather every `<code>` block in lists of some pages to be gather as content and indexed in the search engine :)
