### ISSUE TITLE
Text shown 2 times in the documentation

### ISSUE THREAD

**Issue by LorisHenry** [gama-platform/gama-platform.github.io#194]
Category Constants on page https://gama-platform.org/wiki/UnitsAndConstants is shown twice

**Expected behavior**
Should be shown once

browser : Chrome

**Comment by RoiArthurB** [comment]
I am closing this issue as a duplicate from issue #144

**Comment by lesquoyb** [comment]
very probably related but not sure the fix for one will solve the other so I'm reopening for better tracking
