### ISSUE TITLE
Make documentation MDX2 compliant

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama-platform.github.io#196]
## Is your request related to a problem? Please describe.

In order to fix #179 we need to migrate the website to Docusaurus 3 (about to be released, currently in RC). The main issue is that it requires our markdown files to be compliant to MDX2 (new markdown framework used by default to turn MD to HTML pages). This new version of MDX add some abilities which are conflicting with the way we wrote part of the documentation.

## Describe the solution you'd like

The GHA already uses a Python script to escape some tags ( `escapingTags.py` ) which were already problematic for MDX1, and a simple solution would be to escape some more tags outside code block.

**Technically, it only needs to escape `<` and `{` extra tags**. 

It's also possible to try generated files on this website ( https://mdxjs.com/playground/ ) to check if it would compile well or still have some issues to debug (mind to activate option `remark-directive` and `remark-gfm` to be in the exact same compilation environment as described there : https://docusaurus.io/docs/next/migration/v3#using-the-mdx-playground ).

**Comment by lesquoyb** [comment]
Do you have an example of faulty md file I can use as an example to update the script ?

**Comment by RoiArthurB** [comment]
> Do you have an example of faulty md file I can use as an example to update the script ?

I ran my tests on [OperatorsSZ](https://github.com/gama-platform/gama/wiki/OperatorsSZ), I guess any operator page is complex enough to have all the possible issues from the website.

> Also in the `escapingTags.py`, we only replace the `<` character of html tags that are never closed, is it also the case for `{` now ?

Now those characters are also read for embedding JSX Tags (with `<`) or JavaScript expressions (with `{`): i.e you want to set current year in a markdown page, you can do it with a little js function inside those tags. 

>  Are we only replacing those that don't have a matching `}` or we replace them all ?

No, the detection system is pretty strange and will create issues if the code after the opening tag isn't correct. For example, `[<](OperatorsAA#<)` can't compile as it's not proper code after the tag.

So we need to detect if (1) it's not a proper HTML tag (which won't create any compilation error, and is needed to display our documentation), (2) isn't into a code block (which isn't read by the MDX2 compiler) and (3) no need to search for any closing ones as it won't trigger anything. 

> And by what should we replace them ?

2 options, either you escape them, turning the previous link into `[\<](OperatorsAA#<)`, or by replacing them with html entities ([full list here](https://www.freeformatter.com/html-entities.html), tldr `<` == `&lt;` and `{` == `&#123;`).

**Comment by lesquoyb** [comment]
I pushed a solution on a new branch, please test
