### ISSUE TITLE
Incomplete Tutorial

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama-platform.github.io#21]
Hello,

The tutorial [Co-Modeling Tutorial](https://gama-platform.github.io/wiki/CoModelingTutorial) is incomplete (there is only the skeleton of the tutorial display on the page linked).

Thanks.

**Comment by lesquoyb** [comment]
### **General information to help with the editing of the documentation**
Every wiki page of the documentation can be directly modified at the address : [https://github.com/gama-platform/gama/wiki](https://github.com/gama-platform/gama/wiki) followed by the name of the page and then click on the `edit` button in the top-right hand-corner.
The website will be updated at the next travis build.

For example to update the [https://gama-platform.org/wiki/Home](https://gama-platform.org/wiki/Home) page, we go to [https://github.com/gama-platform/gama/wiki/Home](https://github.com/gama-platform/gama/wiki/Home) and click here :
![image](https://user-images.githubusercontent.com/6374469/159215274-4b086e82-a6e3-4300-b7dd-63bb918b04d0.png)



_So in the case the page to edit would be [https://github.com/gama-platform/gama/wiki/CoModelingTutorial](https://github.com/gama-platform/gama/wiki/CoModelingTutorial)_
