### ISSUE TITLE
missing link for correspondence between gaml and netlogo

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#214]
**Exact broken link**
in page [other concepts](https://gama-platform.org/wiki/Exhaustive-list-of-GAMA-Keywords#other-concepts) the link to [Correspondence GAML and Netlogo](https://gama-platform.org/Introduction#vocabulary-correspondence-with-the-agent-based-paradigm-as-in-netlogo) returns 404

**Comment by RoiArthurB** [comment]
The page should point to https://gama-platform.org/wiki/Introduction#vocabulary-correspondence-with-the-agent-based-paradigm-as-in-netlogo but the link comes from a generated link so I'll let @benoitgaudou manage it :)

**Comment by lesquoyb** [comment]
still 404

**Comment by lesquoyb** [comment]
oops I forgot to force the next version, it is actually fixed
