### ISSUE TITLE
Links in constants and colors page lead to the right page but not the specific section

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#219]
**Exact broken link**
All the links in the [constants and color section](https://gama-platform.org/wiki/next/Exhaustive-list-of-GAMA-Keywords#constants-and-colors) of the keywords page lead to the top of the [units and constants page](https://gama-platform.org/wiki/next/UnitsAndConstants) but not the specific part related to the constant

**Comment by RoiArthurB** [comment]
@benoitgaudou Those links should link to part's title (`3D`, `Constants`, else) from the _Units and constants_ page
