### ISSUE TITLE
Graphical editor page should be updated

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama-platform.github.io#22]
The current page is this one:
https://gama-platform.github.io/wiki/G__GraphicalEditor

By, one more up to date exists:
https://github.com/gama-platform/gama/wiki/G__GraphicalEditor

We should replace the first page by the second one.

**Comment by tcquang** [comment]
I just add this new page to the old website ( In Recipes)
We should update in the new website.

**Comment by tcquang** [comment]
Hello Arthur,
The Graphical Editor page was not updated. It should be this page:
https://github.com/gama-platform/gama/wiki/G__GraphicalEditor
Chers,

**Comment by RoiArthurB** [comment]
I've fixed images, but the page has the same content on the website and on the wiki isn't it?
