### ISSUE TITLE
Constants and colors doesn't contain any color

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama-platform.github.io#220]
As the title says, the section [Constants and colors](https://gama-platform.org/wiki/next/Exhaustive-list-of-GAMA-Keywords#constants-and-colors) doesn't contain any color.
![image](https://github.com/gama-platform/gama-platform.github.io/assets/6374469/47b448a1-abc5-44db-8adb-d6dbe713f37e)

**Comment by benoitgaudou** [comment]
I attempt to fix it on fix-documentation-issues branch.

@RoiArthurB 
Questions before PRing:
- there are 2 files : index.md and Exhaustive-list-of-GAMA-Keywords.md : they are similar to me. I think I generate the latter one. Should we keep the former one?
- Exhaustive-list-of-GAMA-Keywords.md is generating in the root of the gama.wiki folder. Is there a reason why it is not in References/GamlReferences/ as the other generated files ?
