### ISSUE TITLE
Add different World Map related to GAMA

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#24]
It would be great to be able to acces some dynamic map representing different data about GAMA for instance:

- Developper map (who is contributing)
- User Map (ideally could be linked to IP adress)
- Workshop map
 etc etc 

I am starting to look at tools like MapBox or Carto that could be used to realize such a map.
Many example can be found here
https://docs.mapbox.com/mapbox-gl-js/examples/

This is for instance a quick one that I did for CityScience Network

<img width="1413" alt="Screen Shot 2019-04-17 at 15 52 40" src="https://user-images.githubusercontent.com/3928502/56316680-ec25d800-6128-11e9-8f3b-3940eafcec8f.png">

**Comment by RoiArthurB** [comment]
Hello,

The idea is not that bad, but we don't have that kind of data. Every Gama-Platform is downloaded from GitHub and we only have the number of download per release and per version.

If you have any other idea about a map related to gama, I'll be glad to read it, otherwise I'll close the issue.

Thanks :)

**Comment by RoiArthurB** [comment]
Here's all the data that we can use : https://api.github.com/repos/gama-platform/gama/releases

**Comment by agrignard** [comment]
Did you find a way to map it?

**Comment by RoiArthurB** [comment]
As I said above, we don't have in data to do it. We can't access any log from github server (AWS service more precisely) and the only interesting data from the API is the download count..

So if you have any idea on how to do it from that, I'll be glad to help and to try to implement it! 

But I don't see any solution and if you don't I'll just close this great idea here ^^'

**Comment by RoiArthurB** [comment]
@agrignard So if you don't have any solution, I'll close this issue tomorrow
