### ISSUE TITLE
Gama developer teams

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#26]
In the page: [https://github.com/gama-platform/gama/wiki](https://github.com/gama-platform/gama/wiki), the developer teams are introduced, but it seems that they should be updated. For instance, the link to the MSI Research Team web site is no longer working. And Ummisco seems not well introduced (Address, institution, ..)

**Comment by AlexisDrogoul** [comment]
Page updated.
