### ISSUE TITLE
Logo flatted by responsive

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#28]
In full screen, the logo appears OK.
But when reducing the size of the screen, the logo is wrongly resized, to become to thin.

<img width="1104" alt="Capture d’écran 2019-05-10 à 23 28 52" src="https://user-images.githubusercontent.com/1555274/57542290-6a1d7d80-737b-11e9-89b1-a033c31c6bba.png">

**Comment by RoiArthurB** [comment]
Fixed in commit https://github.com/RoiArthurB/BC2019-Gama-Site/commit/9211ebdb159ccd95d35c99af98590b0afece89cc
