### ISSUE TITLE
Changes in the new Version

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#29]
In the page [https://github.com/gama-platform/gama/wiki/New-Version-Changes](https://github.com/gama-platform/gama/wiki/New-Version-Changes) listing the changes in the new version of GAMA, several points have been noted as coming changes. The page needs to be updated. For example : 

**Serialization**
Serialize simulations and replay them (to come)
Serialization and deserialization of agents between simulations (to come)
Allow TCP, UDP and MQQT communications between agents in different simulations (to come)

**Comment by RoiArthurB** [comment]
You've update the page. Can we close the issue now? :)
