### ISSUE TITLE
grouping / excluding plugin operators from GAMA core operators

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama-platform.github.io#32]
**Is your request related to a problem? Please describe.**
There are many operators which belong to a skill/ plugin that are not useful for a general beginner. These are also available or combined together with all other general core operators. 

a beginner browsing through the documentation cannot differentiate if an operator is from the core or from any specific plugin. 

**Describe the solution you'd like**
Group operators of skills/ plugins to a separate page.

**Describe alternatives you've considered**
use an extra `#` to create a sub-section right under operator  that indicates  which plugin the operator belongs to. For example if an operator name has `##` level, a`###` level can mention e.g., `BDI`. Now this can, in markdown syntax  ()[] link to a page ..... GitHub.com/gama-platform/plugins/BDI.wiki

So if I am browsing through the documentation, I quickly notice that it is not the core operator and if I interested further, I can click the hyperlink.

**Comment by RoiArthurB** [comment]
@sriramab I'm sorry, but I really don't understand what you mean...

Could you show me a presentation you'd like to see on the website? Currently, it looks like this : 

```txt
[bool]
Possible uses:

    bool (any) ---> bool

Result:

casts the operand in a bool object.
```

**Comment by benoitgaudou** [comment]
Dear,
The point is that, on the website, only operators of the "core" of GAMA are documented.
"core" here means the release of GAMA.
The notion of plugin  such as  BDI, network ...  are only an internal structuration of GAMA. We do not need to highlight it in the documentation.
But in the operators' documentation, there are some categories (beginning of the page), that mentions all the operators related to BDI, to statistics. ... 

Cheers
