### ISSUE TITLE
FIPA documentation somewhat lacking

### ISSUE THREAD

**Issue by lodo1995** [gama-platform/gama-platform.github.io#34]
The documentation for FIPA is somewhat lacking. For a newbie in the field, it is almost impossible to use.

I'm refering to [Using FIPA ACL](https://gama-platform.github.io/wiki/UsingFIPAACL) and [Built-in Skills](https://gama-platform.github.io/wiki/BuiltInSkills#fipa). I could not find any other resource regarding FIPA in GAMA.

**Things that should be fixed in the docs**

- The first page describes the variable `messages` as a list containing messages for all performatives; as of GAMA 1.8 RC 2, this variable does not appear to exist; it might have been renamed to `mailbox`; the second page, on the other hand, does not talk about either `messages` or `mailbox`.

- There is no documentation for the fields of the `message` type. What can I access through it? Contents? Performative? Sender? Protocol? Send time? Delivery time? Reference to the conversation?

- There is no documentation for the fields of the `conversation` type. What can I access through it? Participants? Map of the last message for each participant? Start time? Protocol?

- For each performative there is a variable containing its messages. But how can I access the contents of `end_conversation` messages? No specific variable is documented for that. Can I only access them through the `mailbox`?

- Might be obvious to experts in the field, but it might be worth specifying that messages are removed from all the lists they appear in, once they are replied to by using one of the provided methods.

- Formatting of the documentation appears to be broken (pieces of sentence missing, pieces of markup code appearing as text), but this might be worth another issue, as it is not limited to the FIPA page, but extends to many pages of the GAMA docs, sometimes in a very disruptive way.

**Comment by LedanDark** [comment]
Seconded. 
Students using this 2 years later are running into the exact same issue.

**Comment by lesquoyb** [comment]
### **General information to help with the editing of the documentation**
Every wiki page of the documentation can be directly modified at the address : [https://github.com/gama-platform/gama/wiki](https://github.com/gama-platform/gama/wiki) followed by the name of the page and then click on the `edit` button in the top-right hand-corner.
The website will be updated at the next travis build.

For example to update the [https://gama-platform.org/wiki/Home](https://gama-platform.org/wiki/Home) page, we go to [https://github.com/gama-platform/gama/wiki/Home](https://github.com/gama-platform/gama/wiki/Home) and click here :
![image](https://user-images.githubusercontent.com/6374469/159215274-4b086e82-a6e3-4300-b7dd-63bb918b04d0.png)



_So in this case the pages to edit would be : [https://github.com/gama-platform/gama/wiki/UsingFIPAACL](https://github.com/gama-platform/gama/wiki/UsingFIPAACL) and the documentation in the gama code as the page [Built-in Skills](https://gama-platform.github.io/wiki/BuiltInSkills#fipa) is automatically generated_

**Comment by benoitgaudou** [comment]
The documentation of the FIPA skill has been totally rewritten:
 * [Using FIPA ACL](https://gama-platform.github.io/wiki/UsingFIPAACL) describes step by step how to use the FIPA skill. It has also been extended to describe the  2 relevant Data Types (message and conversation).
 * [Built-in Skills](https://gama-platform.github.io/wiki/BuiltInSkills#fipa) contains the exhaustive documentation of  all the attributes and actions.

I tried also to integrate all the remarks!

Thank you for this careful and complete review of the documentation.

**Comment by lesquoyb** [comment]
From a newbie's point of view it looks very complete, thanks
