### ISSUE TITLE
Link to the model is missing:

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#38]
In the page: [https://github.com/gama-platform/gama/wiki/ThreeD_step2](https://github.com/gama-platform/gama/wiki/ThreeD_step2),   Section: Complete Model, 
the link to the model is Broken [(https://github.com/gama-platform/gama/tree/master/msi.gama.models/models/Tutorials/3D/models/Model).](https://github.com/gama-platform/gama/tree/master/msi.gama.models/models/Tutorials/3D/models/Model) Model missing.

**Comment by RoiArthurB** [comment]
Link fixed ;)
