### ISSUE TITLE
Link to model is missing

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#39]
In the page: [https://github.com/gama-platform/gama/wiki/ThreeD_step3](https://github.com/gama-platform/gama/wiki/ThreeD_step3), the link to the model in the Complete model section is broken: [https://github.com/gama-platform/gama/tree/master/msi.gama.models/models/Tutorials/3D/models/Model](https://github.com/gama-platform/gama/tree/master/msi.gama.models/models/Tutorials/3D/models/Model)

**Comment by RoiArthurB** [comment]
Link fixed ;)
