### ISSUE TITLE
Pages last line is quite often  //: # (end something)

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama-platform.github.io#4]
For most of the pages, at the end of the page, there is this kind of text : 
 //: # (endConcept|export_files)

We need to remove from display (at least).

**Comment by dphilippon** [comment]
This seems to be from the wiki in github of gama-platform... Might be a problem of the mardown compiler.

**Comment by RoiArthurB** [comment]
Hi, the problem is not solved on every pages.
For example the problem is still on this page : https://gama-platform.github.io/wiki/CallingR

**Comment by dphilippon** [comment]
Hi, 
Yup, I have found a solution, which is to change from kramdown to redcarpet, but I changed it back because github only want kramdown from now. (love it)

**Comment by RoiArthurB** [comment]
Problem solved with the version 1.8 website
