### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#40]
in the page: [https://github.com/gama-platform/gama/wiki/ThreeD_step1](https://github.com/gama-platform/gama/wiki/ThreeD_step1), the link : [https://github.com/gama-platform/gama/tree/master/msi.gama.models/models/Tutorials/3D/models/Model](https://github.com/gama-platform/gama/tree/master/msi.gama.models/models/Tutorials/3D/models/Model) is broken.

**Comment by RoiArthurB** [comment]
Link fixed ;)
