### ISSUE TITLE
link broken in: LuneraysFlu page. 

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#41]
in the web page: [https://github.com/gama-platform/gama/wiki/LuneraysFlu](https://github.com/gama-platform/gama/wiki/LuneraysFlu), the first link in the first paragraph is broken.

**Comment by RoiArthurB** [comment]
The link is working, it makes you download a ZIP archive with the Lunerays Flu tutorial inside :)
