### ISSUE TITLE
Image missing in the page: InstallingPlugins

### ISSUE THREAD

**Issue by YoucefSklab** [gama-platform/gama-platform.github.io#44]
In the page  [https://roiarthurb.github.io/BC2019-Gama-Site/wiki/InstallingPlugins](https://roiarthurb.github.io/BC2019-Gama-Site/wiki/InstallingPlugins) There is a missing picture.

This happens when two pages are side by side,  all over the web site.

**Comment by RoiArthurB** [comment]
Fixed here RoiArthurB/BC2019-Gama-Site@54e04804cf511a75b98e416cdd66ea5002e7c2d8
