### ISSUE TITLE
Multiple issues under Safari for Front Page

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#45]
- coloured buttons are not left-aligned with the text (maybe it is the case elsewhere, but the visual effect is odd, as if elements were put randomly)
- GIF seems to be loading but it's not playing.

**Comment by AlexisDrogoul** [comment]
Thanks ! One more thing, if possible: what about adding a bit of space on top of the page, so that the text and the logo are almost centered vertically on the page ?

**Comment by RoiArthurB** [comment]
I can try something.

The problem is that the gif won't fit in the page without scrolling in that case. 
Also it will be very difficult to have it really center on every screens... :/

**Comment by RoiArthurB** [comment]
Fixed here e935066f71eeb8d1b1eb2a1cfe5cd863f6697797
