### ISSUE TITLE
Change download page

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#46]
<img width="572" alt="GAMA-Platform · GAMA 2019-05-14 21-57-09" src="https://user-images.githubusercontent.com/579256/57709339-05249900-7695-11e9-9d0c-41c62de90d01.png">

**Comment by RoiArthurB** [comment]
Fix in commit 8b264554da1f10c4faadbaad02818a784c33f8e3

You can close the issue if you enjoy the redesign :)

**Comment by AlexisDrogoul** [comment]
Nice step !  👍 

2 more things, however: 

1. Simplify the text as in the image I put in the first comment (ie. only "Download" and "The latest stable... etc."
2. Make the documentation button the same size as the other buttons, and aligned on the first column, as well, with "Documentation" the same size as "Windows", "Apple" and "Linux", and the text of the button  simply "PDF".

**Comment by RoiArthurB** [comment]
Oups, I haven't notice all the littles differences...
Everything has been fixed in the last commit ( 56bc5987 ) close the issue if everything is fine now :)

**Comment by AlexisDrogoul** [comment]
To make myself clearer:

<img width="585" alt="GAMA-Platform · GAMA 2019-05-16 15-45-09" src="https://user-images.githubusercontent.com/579256/57840155-4aaaa880-77f2-11e9-8909-0b8daac2d83d.png">


And replace the upper text by the one present on the first image ("The latest stable version of GAMA can be downloaded with or without an embedded JDK. If you feel adventurous, you can also try the daily release").

**Comment by RoiArthurB** [comment]
Yes yes, I've fixed it all ! :)
Travis just take 10 minutes between the commit and the changes on the website ^^

So I've modified the last bad elements, check in 10 minutes if the 5bcb1bae3461b70b3cc370bae1a876f4eb52c791 commit solved everything ^^

**Comment by AlexisDrogoul** [comment]
Cool ! Two small details : "Apple" -> "macOS" / and maybe center "Documentation"... Other than that, perfect !
