### ISSUE TITLE
empty section in autogenerated documentation

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama-platform.github.io#48]
Hi

In the auto generated documentation, there is a blank section in all pages of the operators. The second section is always blank in all pages. I think by mistake, there is a misplaced # tag that creates this empty section.

Please modify, I cannot modify because it says auto-generated and do not modify.

**Comment by RoiArthurB** [comment]
Hello,

I don't find any page with that `<br />` tag... Can you link me a page with that error please?

**Comment by RoiArthurB** [comment]
Ok I found it and fixed it :)
