### ISSUE TITLE
No results when taping "batch" in the search bar

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#51]
I don't if it's because it's not documented or not parse but 0 results appear when typing ````batch````in the search bar.

It's the first world I was playing with I guess there is a lot of case like that, how to we proceed shoudl post an issue for each case like this?

**Comment by RoiArthurB** [comment]
The search engine is in active development. It's currently lacking a lot of keywords, but they will be added as soon as possible!

**Comment by RoiArthurB** [comment]
Duplicate of #36
