### ISSUE TITLE
Search Engine: remove items in concepts with duplicated url

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#54]
When I search for batch in the search bar, I get:
![Capture d’écran 2019-05-18 à 09 25 57](https://user-images.githubusercontent.com/1555274/57963500-23b5b900-794f-11e9-9af5-c6e6d5f17871.png)

The 2 items in `concept actions` and `concept condition` are already presented in Statements, and should not be presented.

So would it be possible to remove the items in concepts for which the url field in already presented in another item presented ?

**Comment by RoiArthurB** [comment]
Do you want to avoid duplicated elements only for _Concepts_ category or for every links?

**Comment by benoitgaudou** [comment]
Perhaps I am wrong, but I have the feeling that duplicate can only be in
Concepts and not in the other ones.
Am I right ?

Cheers

Benoit

Le lun. 20 mai 2019 à 10:01, Arthur Brugiere <notifications@github.com> a
écrit :
