### ISSUE TITLE
Usefullness of the keywords: [//]: # (keyword|species_graph_node)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#55]
I can observe that some pages have the following symbols generated:
```
[//]: # (keyword|species_graph_node)
```

e.g.: [https://gama-platform.github.io/wiki/BuiltInSpecies#graph_node](https://gama-platform.github.io/wiki/BuiltInSpecies#graph_node)

I was wondering whether they are still used by something ?

**Comment by RoiArthurB** [comment]
Hello,

It was used with a previous search engine, but I have no use of it with the last website. So you can remove it from the generation (it will be better on website and GitHub wiki) :)

**Comment by benoitgaudou** [comment]
It should have been fixed by commit: 
https://github.com/gama-platform/gama/commit/0efdb885783c7c261858638cb576cf2d3cefac00
