### ISSUE TITLE
Unix install

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama-platform.github.io#58]
The documentation to install gama on unix system (Ubuntu, Manjaro, etc) should be updated

**Comment by RoiArthurB** [comment]
https://github.com/gama-platform/gama/wiki/Installation/b2a50b6223d2b6cc9912ab7dd93526111c506a3a

**Comment by hqnghi88** [comment]
Hello Arthur,
I am really wonder about Installing OpenJDK section in the page. I think if we place there, users will assum that we support the openJDK, instead we replace by more details on Oracle JDK on ubuntu, not a link, but the tested tutorial for installing.
I did by read your link, and go to next link https://askubuntu.com/questions/56104/how-can-i-install-sun-oracles-proprietary-java-jdk-6-7-8-or-jre
Install Java JDK
The manual way

    Download the 32-bit or 64-bit Linux "compressed binary file" - it has a ".tar.gz" file extension.

    Uncompress it

    tar -xvf jdk-8-linux-i586.tar.gz (32-bit)

    tar -xvf jdk-8-linux-x64.tar.gz (64-bit)

    The JDK 8 package is extracted into ./jdk1.8.0 directory. N.B.: Check carefully this folder name since Oracle seem to change this occasionally with each update.

    Now move the JDK 8 directory to /usr/lib

    sudo mkdir -p /usr/lib/jvm
    sudo mv ./jdk1.8.0 /usr/lib/jvm/

    Now run

    sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0/bin/java" 1
    sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.8.0/bin/javac" 1
    sudo update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.8.0/bin/javaws" 1

    This will assign Oracle JDK a priority of 1, which means that installing other JDKs will replace it as the default. Be sure to use a higher priority if you want Oracle JDK to remain the default.

    Correct the file ownership and the permissions of the executables:

    sudo chmod a+x /usr/bin/java
    sudo chmod a+x /usr/bin/javac
    sudo chmod a+x /usr/bin/javaws
    sudo chown -R root:root /usr/lib/jvm/jdk1.8.0

    N.B.: Remember - Java JDK has many more executables that you can similarly install as above. java, javac, javaws are probably the most frequently required. This answer lists the other executables available.

    Run

    sudo update-alternatives --config java

    You will see output similar to the one below - choose the number of jdk1.8.0 - for example 3 in this list (unless you have have never installed Java installed in your computer in which case a sentence saying "There is nothing to configure" will appear):

    $ sudo update-alternatives --config java
    There are 3 choices for the alternative java (providing /usr/bin/java).

      Selection    Path                                            Priority   Status
    ------------------------------------------------------------
      0            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      auto mode
      1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
    * 2            /usr/lib/jvm/jdk1.7.0/bin/java                   1         manual mode
      3            /usr/lib/jvm/jdk1.8.0/bin/java                   1         manual mode

    Press enter to keep the current choice[*], or type selection number: 3
    update-alternatives: using /usr/lib/jvm/jdk1.8.0/bin/java to provide /usr/bin/java (java) in manual mode

    Repeat the above for:

    sudo update-alternatives --config javac
    sudo update-alternatives --config javaws

**Comment by AlexisDrogoul** [comment]
Absolutely agree. We do not (and cannot) support OpenJDK. GAMA runs partially under it and there is no plan to improve this state of affairs...

**Comment by RoiArthurB** [comment]
Actually, I've always used GAMA with OpenJDK 8 and it works well. 
The only problem that I had is to build Git version of GAMA (but I'm not even sure if it's related to the JDK or something else).

So remove the OpenJDK if you want, but I really think that it's a great way to run GAMA on Unix OS

**Comment by AlexisDrogoul** [comment]
Well -- I have read elsewhere (by @benoitgaudou , I think) that reading shape files might be a problem under OpenJDK. Anyway, if it works, even partially, we can always put a big warning sentence at the beginning of this section, saying that OpenJDK is not the recommended way to run GAMA and that it is not (and won't be) supported...

**Comment by RoiArthurB** [comment]
There's no much difference between OpenJDK and Oracle JDK (OpenJDK is maintained by Oracle themself and many other big team like Red Hat https://en.wikipedia.org/wiki/OpenJDK ).

@AlexisDrogoul Ok I'll add a warning at the beginning of the section :)

**Comment by RoiArthurB** [comment]
https://github.com/gama-platform/gama/wiki/Installation/cf99aa156a5e294ffdc678dfb666d52dcb35e98b

Close the issue if you like the warning message ^^

**Comment by hqnghi88** [comment]
@RoiArthurB It seems until now you are the best expert unix gama developer, so yes you can keep the section with A BIG WARNING at the beginning. But as i said, the Oracle section must be more details, as if user read the long way to install Oracle, they are tired to try the optional OpenJDK :) . And in Open jdk, for debian, i found that you install only jre, which should be better a jdk
sudo apt-get install openjdk-8-jdk
And contrary , i propose that you switch to use Oracle JDK from now , to see if we will have another results of openjdk vs oraclejdk?

**Comment by RoiArthurB** [comment]
@hqnghi88 Ok I've fixed the command line for OpenJDK/Ubuntu

And I don't understand your suggestion.. Do you want me to try using GAMA with Oracle JDK 8 and see if I have any issue using it than OpenJDK 8 ? 
'Cause, if you develop GAMA for Oracle JDK it should have same bugs than on MacOS (same JVM kernel execution). So using OpenJDK should be more buggy (which is not) :thinking:

**Comment by hqnghi88** [comment]
:) No real unix developer for Gama so far , so i m afraid not to have enough testing, that's why we scare about openjdk.
How about the OracleJDK section? do you think the 2 link provided is clear enough? If yes we can consider this issue as closed

**Comment by RoiArthurB** [comment]
I'm not a JDK expert, but as far as I know, OracleJDK is almost exactly the same as OpenJDK (not on the techno way, but in the used). So we can use one or the other without any trouble (in theory at least).
So the important point (from my pov) is to install version 8, not having Oracle or Open.

And I think it's enough. The big problem is that Oracle licence changed, so there's a lot of workaround but no official way to install it. So with the Ubuntu link, we have documentation to latest Ubuntu version (Ubuntu 19.04) which is marked as duplicate of a 7 years old page. 
So I think that we cover well Ubuntu OS. ^^

**Comment by RoiArthurB** [comment]
I've created a PPA (for ubuntu) to install gama w/ and w/o JDK !
See here https://github.com/gama-platform/gama/issues/2767

**Comment by AlexisDrogoul** [comment]
Subsumed by #96 and the adoption of Temurin on all platforms
