### ISSUE TITLE
Access the new feature of GAMA 1.8 on the website

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#59]
@RoiArthurB Is it possible to have an access on the website to the new feature of GAMA?

I remember you started an html file but right now we cannot access to it from the website

Here is the content
https://docs.google.com/document/d/1rhgop9PHvsmg86hroyBjiP_TSMfKLer6UBdxgHxS0rk/edit

Maybe we can have a "What's New" button?

**Comment by RoiArthurB** [comment]
Hello,

You've right, I've already created a page with a short text to announce the new release here : https://gama-platform.github.io/release-1.8

You can access the link by clicking on the GIF in the website's front page (I know this is not UI/UX friendly, but I'm waiting the _true_ release to add a label on top of the GIF to let people click on it ;) )

Does the text is ready? @AlexisDrogoul told me not to..

**Comment by agrignard** [comment]
Ah ok perfect! So let's keep like that for now. 

I am trying to work on some icon for every item, You can maybe prepare the html page (maybe having 2 in //) in term of layout so it can display one little icon close to each bullet point? Actually I don't exactly the layout we want but you see what I mean?

**Comment by RoiArthurB** [comment]
If you can gave me dimensions of your icons I can work on the layout :)

**Comment by agrignard** [comment]
OK so here is a kind of first design proposal (open to discussion as usual ;-)). That can also evolve in this https://unity.com/fr with a mouse over effect

<img width="731" alt="Screen Shot 2019-06-05 at 3 33 21 PM" src="https://user-images.githubusercontent.com/3928502/58984643-84465200-87a7-11e9-8279-e4226c480d1c.png">


Right now we have 12 items so the idea would be to make a 4x3 Grid and each grid would have an icon and the corresponding text.

A colleague of mine is willing to help of the design of the icon, @RoiArthurB the idea would be to have 12 icon.png, that you could extract from here (ideally that will we send). If you can place them somewhere in the github then we can dynamically update the icon
[png.zip](https://github.com/gama-platform/gama-platform.github.io/files/3258759/png.zip)

There is still some icon where don't knwo exacty what to put (especilly co-modelling, serialization and multi simulations) but we are working on it and open to proposition.

**Comment by AlexisDrogoul** [comment]
Interesting, but not what I had in mind. Having abstract icons that
paraphrase the text does not carry any new information or 'desire to test'
compared to plain text. There is no real point, in my opinion, in having
pictures (or icons) if they don't reflect the platform or models, or
illustrate the text itself by depicting something that people can see when
they use the platform - the goal being to make them want to try it. If you
feel it is too complicated for some items, then let's stick with the text
list.


Le jeu. 6 juin 2019 à 02:38, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
The idea is too have (as requested in one on your mail) something better than just the bullet point. Paraphrasing with abstract icon is usually always not worth than just boring text ans to my opionion pretty powerfull (assuming the icon are well designed)

So I don't get what was your request? You want "vignette" coming directly from GAMA (in this case there is some of them that are very hard to conceptualized)? Again this proposal is just a place older after we can put Icon or something else it just has to be coherent and better than a simple list

**Comment by AlexisDrogoul** [comment]
Yeah, vignettes coming directly from GAMA, in order to **show** something, not just talk about it. Abstract icons do not carry any information for this type of communication. But maybe just a nice background like the one we used to have (with the 2 perspectives in ... perspective) will be enough.

**Comment by agrignard** [comment]
Ok I see . Which means that in any case @RoiArthurB if you have time you can start the layout using this grid concept? Maybe in a separate hmtl file for now while it's working in progress and we can populate it step by step.

**Comment by RoiArthurB** [comment]
I'm not sure to get what you want. Could you firstly create a wireframe of the website so I just have to implement it?
Or the design is just a grid with some background image/gif/whatever with text on-top of it?

**Comment by AlexisDrogoul** [comment]
Quick sketch -- better images are required (if you have any nice simulation perspectives... could be nice to make a gif too)

![image](https://user-images.githubusercontent.com/579256/59042529-cf925a80-88a4-11e9-88aa-f60ea3216995.png)

**Comment by RoiArthurB** [comment]
Do you want a design similar to this ? 
![image](https://user-images.githubusercontent.com/16764085/59208046-84dd4f00-8bd2-11e9-84de-a5863a4a72a4.png)

(I have to admit, I have no idea about where the image come from.. It was simply in my Firefox highlights related to something totally different... xDD )

**Comment by hqnghi88** [comment]
I like this, but if it can have some transform effect on each small square to show the difference, enhancement, it would be perfect

**Comment by ptaillandier** [comment]
It's not really relevant anymore.
