### ISSUE TITLE
Add GAML in standard repository languages

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#61]
In a GitHUb repo, github can recognize automatically the langage use (java, python, etc), however it's not able (yet?) to recognize GAML 

The way to do it is to update the Github repository languages.

Starting point is here:
https://help.github.com/articles/about-repository-languages/

What do you think? I think it make sense to add GAML in this folder, I was thinking that maybe @hqnghi88 you could be interested to do it?

**Comment by RoiArthurB** [comment]
@nghi At least we can add GAML as an existing langage and just use Java coloring in it. 

That way, we can start to request repository using GAML in GitHub and project will have a basic syntax colorization ! :smiley:

**Comment by AlexisDrogoul** [comment]
Good idea !

**Comment by hqnghi88** [comment]
@RoiArthurB already done long time ago (i was a bit surprise when this issue reappear by an email of Arnaud :)) see https://github.com/gama-platform/gama/commit/e7480d50fb22d45f00cbb2dabb3764e23445f643 and a gaml in github https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Tutorials/Road%20Traffic/models/Model%2007.gaml . 
For further implementation, if you can finish a css color ( i have a small one for gama web) as in Coding camp you asked Benoit, we can see how we request github for new language.

**Comment by RoiArthurB** [comment]
@hqnghi88 Yes, but I was talking about adding GAML in Linguist (which is not the case, you can check [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)). So Github will detect in the front bar of the project how much pourcent is GAML in the repo.

![image](https://user-images.githubusercontent.com/16764085/59008562-0d679280-8855-11e9-9abb-78cb4a0d06df.png)

The link that @agrignard send was about that I think
> GitHub uses the open source _Linguist_ library to determine file languages for syntax highlighting and **repository statistics**.

Also, I'm working on the syntax highlight for another plugin ( https://highlightjs.org/ ) which have it's own grammar. So for now I don't have any kind of CSS to give you. 
And I've took a quick look at Linguist, but I haven't find any doc about syntax highlighting..

-> So if you want I can do the pull request to add GAML as a language in Linguist and, later, work on syntax highlighting to have some beautiful repo all over GH :sunglasses:

**Comment by hqnghi88** [comment]
Sorry, i think you talk about coloring gaml as same as java syntax.  So now if i get you , you mean add Gaml as a new type  in that bar (java 95.2 and should be gaml 10%?...)
For that purpose, i said in previous comment, there is a linguist compiler on github server compile file type with corresponding syntax compiler. See
https://github.com/github/linguist/blob/master/vendor/README.md for the list and for example 
Netlogo use lisp https://github.com/textmate/lisp.tmbundle
and Java https://github.com/textmate/java.tmbundle
So , firstly we must have something on textmate and then validate it by linguist and the pull request to github to add our language type. in fact it is not very complicated but take time.
And in that case some one must play with the syntax compiler in textmate (as 2 example link above). If you want to use the java coloring syntax, see how netlogo (lisp) and even any gaml example (java based). 

AT LAST, if you can request a new GAML element in that bar above , it is already not bad beginning.

**Comment by RoiArthurB** [comment]
Ok so I'm working on adding GAML as a language in Github (later i'll work on linking the GAML syntax).

So I need to confirm some informations (base on the [documentation](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) and the definition on metadata [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)) :
 - [x] Language Name _GAML_ (in uppercase) 
 - [ ] fs_name (Optional) -> **blank**
 - [x] type _programming_
 - [ ] aliases (Optional) -> **blank**
 - [x] ace_mode_text_
 - [ ] codemirror_mode (Optional) -> **blank**
 - [ ] codemirror_mime_type (Optional) -> **blank**
 - [x] wrap -> **default** _false_
 - [x] extensions  (array)
   - _".gaml"_
 - [ ] filenames (Optional) -> **blank**
 - [ ] interpreters (Optional) -> **blank**
 - [ ] searchable -> **defaults** _true_
 - [ ] language_id **blank**
 - [x] color _"#EEB64F"_ (the light orange from the logo)
 - [x] tm_scope _none_
 - [ ] group (Optional) -> **blank**

I'll set only checked items in that list.

Also, Linguist ask for some samples (preferably some "real world" code), so I'll add tutorials code.

**Comment by hqnghi88** [comment]
I prefer type modeling (if it's possible) than programming :D . Anyways i remember (not clearly) that we must also give them (github) some real world repos that use gaml than our .

**Comment by RoiArthurB** [comment]
@hqnghi88 For the type we have to choose one of them
> # type                  - Either data, programming, markup, prose, or nil

And yes, I have everything ready to send. Here's the link to show that GAML is used in more than hundreds projects : https://github.com/search?q=extension%3Agaml+NOT+nothack&type=Code ^^

**Comment by agrignard** [comment]
Yes I was refering the addition of GAML in linguist. 

@RoiArthurB there is indeed few step to do so. This is great if you can take care of that 

There is also a tool that can give you all the repo on github that uses Gaml (I don't remember which one but it's documented on the linguist project) I guess you can provide also the model libray as example.

**Comment by RoiArthurB** [comment]
I'm on it. I've forked the Linguist project, and I'll do a Pull Request to add GAML as a recognized extension file.
I'll keep you in touch on this issue.

**Comment by RoiArthurB** [comment]
Hello all o/

I've forget to link my pull request to add GAML file extension to Linguist. Here's the PR : https://github.com/github/linguist/pull/4549
Maybe you could add some good commentary (as Nghi did) to accelerate the process, but (based on previous similar PR) it will take some weeks ^^

Also, if we want to add GAML as a language, we should change the licence as [one of this one](https://github.com/github/linguist/blob/257425141d4e2a5232786bf0b13c901ada075f93/vendor/licenses/config.yml#L2-L11).

**Comment by hqnghi88** [comment]
Dear @gama-platform/committers , could you please give a review in https://github.com/github/linguist/pull/4549/files#submit-review to accelereate the process of github linguist team for our request about adding gaml syntax to github.
Thanks

**Comment by RoiArthurB** [comment]
Hi everyone!
My PR has been merged! :smiley: 

So the `*.gaml` extension file will be automatically recognized in your Github's repo very soon (just have to wait for the next release of linguist package) ^^

So I close this issue and the next step is to add the color highlight to Github ^^

**Comment by agrignard** [comment]
Yes I saw that! thank you for the big effort!

**Comment by RoiArthurB** [comment]
![image](https://user-images.githubusercontent.com/16764085/64011015-07780980-cb45-11e9-94f0-6813240d0545.png)

@gama-platform/core Done! :smile: 
GAML files will be indexed if you've made a commit from 3 days ago :yum: 

PS: the screenshot comes from the [gama](https://github.com/gama-platform/gama) repository

**Comment by agrignard** [comment]
Great!!!!
