### ISSUE TITLE
Contribute and Overview Redondance in the wiki

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#62]
Not exactly a bug but maybe it's worth mentioning it to facilitate the maintenance of the website.

There is some information duplication between this wiki page
https://github.com/gama-platform/gama/wiki/Contribute (which I guess is the one use for the website https://gama-platform.github.io/wiki/Contribute

And this wiki page https://github.com/gama-platform/gama/wiki/Overview where the contributor are also repeated (that means that any update in one page needs also to be done in the other). Is it because of the structure of the wiki or do we want to fix it?

**Comment by RoiArthurB** [comment]
Hi,
Because we can't include a MD into another one in GH's wiki, we have to leave this duplication if we want to display this information on both pages :confused: 
If you have any idea about how to improve it, feel free to explain it otherwise I'll have to close this issue..

**Comment by agrignard** [comment]
What about a simple easy and quick solution to avoid duplicating information:

Remove the contributor list form the Contribute page? And keep the contributor in the overview one? 

Happy to do it if no one is against

**Comment by RoiArthurB** [comment]
Why not, and feel the Contribute page with more links and informations to contribute to GAMA (either on the Java code, documentation re-writting, etc) !

I let you do it all as you proposed yourself :wink:
