### ISSUE TITLE
Gamaweb's Model demonstration directly by clicking the link on website

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama-platform.github.io#66]
@RoiArthurB I am working on the capability to show gamaweb with models by clicking on a link on the website (firstly with tutorial model then whole library). Do you have an own way to sort/organise the tutorial models (https://gama-platform.github.io/wiki/Tutorials) or do you have idea where the linking with gamaweb should display?

**Comment by RoiArthurB** [comment]
Hi ! The script to create all the sidebar is here : https://github.com/gama-platform/gama-platform.github.io/blob/sources/script/sidebarCopy.php
To explain it a little, it's based on the `_Sidebar.md` from the Github's Gama wiki. On the process, I create 2 separate sidebar for the website : One for documentation and one for Tutorials.

So how tutorials links are organised. I've noticed that every tutorials are structure like this :
 * Tutorial name (with link matching the name. eg `TutorialName`)
 * First chapter : Base URL + `_stepXX` (eg `TutorialName_step1`)
And so one 'til the last chapter.

So if you want to generate link, you just have to create the tutorial name (with first letter of every word in caps and without space) followed by `_step` + the chapter number :)

**Comment by RoiArthurB** [comment]
@hqnghi88 can I close the issue or do you still need help for you problem? :)

**Comment by hqnghi88** [comment]
Yes, for the moment.
