### ISSUE TITLE
External Model contribution

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#67]
What about having an easy way to share model directly from the website
https://gama-platform.github.io/wiki/Contribute

Ideally, people could easily get and push here
https://github.com/gama-platform/gama.models.experimental

**Comment by RoiArthurB** [comment]
I'm not sure to understand well your request.
Do you want to add a part to explain how to share models and where? If so, you can add it by yourself here : https://github.com/gama-platform/gama/wiki/Contribute
The Contribute webpage is automatically generated from the Gama GH's wiki (you can know it with the "wiki" keyword in the URL : https:\/\/gama-platform.github.io/ ***wiki*** /Contribute :wink:  )

**Comment by lesquoyb** [comment]
done
