### ISSUE TITLE
Tutorial website no synchro with the real model 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#69]
I don't know if there is a historical reason but I prefer to notify it, the tutorial on the website and the actual code in the release are not exactly the same in Road Traffic Tutorial for instance first step.

**Comment by RoiArthurB** [comment]
Tutorials are not generated, so we have to update code by hand. If you want to fix it, you just have to update Gama Github's wiki :)

**Comment by lesquoyb** [comment]
I updated the library models for Prey/predator and BDI, as well as the wiki for Luneary's flu, Prey/predator, Incremental model and BDI. I didn't see anything in the Road Traffic tutorial.
Closing it for now but feel free to reopen if you find something missing
