### ISSUE TITLE
Add a FAQ section with a nice layout

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#77]
It would be nice (and more and more important, see for instance https://github.com/gama-platform/gama/issues/2936) to have a true FAQ section, that could be easily filled by the developers / uses / maintainers of GAMA. 

There are probably many plugins that can fulfil this need, we just need to find one that works easily !

**Comment by RoiArthurB** [comment]
Do you have something precise in mind?

The first idea of layout would be something like this ([real website example](https://www.prepbootstrap.com/bootstrap-template/faq-example)) :
![image](https://user-images.githubusercontent.com/16764085/74725732-4166d480-5279-11ea-9ab6-7ecd0a571fc5.png)

And behind that just a very simple JSON file to edit like below  : 
```
{
    "faq": [
        {
            "question": "My first question",
            "answer": "My first answer"
        },
        {
	    "question": "My second question",
	    "answer": "My second answer"
	},
	{
	    "question": "My third question",
	    "answer": "My third answer"
	}
    ]
}
```

**Comment by AlexisDrogoul** [comment]
That would be great.

**Comment by RoiArthurB** [comment]
I'm thinking... If you want to write long answers with images etc, a JSON file may not be the best file format to do so... 🤔🤔🤔 

I'll take a closer look to all our possible solutions, but for the web page layout we can go with this one !

**Comment by RoiArthurB** [comment]
![image](https://user-images.githubusercontent.com/16764085/75106289-c6753380-5655-11ea-870b-cb6028a8bbdf.png)
Added in the merge https://github.com/gama-platform/gama-platform.github.io/commit/c51a26d9b895aaab06340e3f9563c07cb230d1e2
