### ISSUE TITLE
FAQ : add questions : how to ensure reproductibility of a model ?

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#78]
**Is your request related to a problem? Please describe.**
Now we have a great FAQ, we need to provide an answer to: 
"how to ensure reproductibility of a model ?"

**Describe the solution you'd like**
Describe the various preferences that should be set to the correct value.

**Comment by hqnghi88** [comment]
as FAQ, it's nice to add "what" before "how", i think? :D

**Comment by lesquoyb** [comment]
### **General information to help with the editing of the documentation**
Every wiki page of the documentation can be directly modified at the address : [https://github.com/gama-platform/gama/wiki](https://github.com/gama-platform/gama/wiki) followed by the name of the page and then click on the `edit` button in the top-right hand-corner.
The website will be updated at the next travis build.

For example to update the [https://gama-platform.org/wiki/Home](https://gama-platform.org/wiki/Home) page, we go to [https://github.com/gama-platform/gama/wiki/Home](https://github.com/gama-platform/gama/wiki/Home) and click here :
![image](https://user-images.githubusercontent.com/6374469/159215274-4b086e82-a6e3-4300-b7dd-63bb918b04d0.png)

The FAQ accessible from the url [https://gama-platform.org/faq](https://gama-platform.org/faq) is editable directly on the file [https://github.com/gama-platform/gama-platform.github.io/blob/sources/website/faq.md](https://github.com/gama-platform/gama-platform.github.io/blob/sources/website/faq.md) following the instructions given in the commented section of the file



_So in this case there are two pages to edit : [https://github.com/gama-platform/gama-platform.github.io/blob/sources/website/faq.md](https://github.com/gama-platform/gama-platform.github.io/blob/sources/website/faq.md) and  [https://github.com/gama-platform/gama/wiki/FAQ](https://github.com/gama-platform/gama/wiki/FAQ)_
