### ISSUE TITLE
Update the website front-page and others to target 1.8.1

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#83]
**Is your request related to a problem? Please describe.**
Right now, the download page(https://gama-platform.github.io/download), release page (https://gama-platform.github.io/release-1.8), as well as the front page (with the broken GIF, due to my fault !), point towards the 1.8 release of GAMA. 

**Describe the solution you'd like**
That all these pages point towards the new 1.8.1 release, in the same conditions, and that the CHANGELOG.MD page present in the 1.8.1 directory (https://github.com/gama-platform/gama/blob/GAMA_1.8.1/CHANGELOG.md) is used for the contents of an intermediate page (much like the page at https://gama-platform.github.io/release-1.8 ) announcing the release of 1.8.1.

**Comment by RoiArthurB** [comment]
I'll wait for the 1.8.1 version to be stable and official released before updating the website.

Below all the pages needed to be updated : 
- [ ] https://gama-platform.github.io/
  - GIF's link
- [ ] https://gama-platform.github.io/release-1.8
  - [ ] First update content to 1.8.1
  - [ ] Second Automatically update with [Changelog file](https://github.com/gama-platform/gama/blob/GAMA_1.8.1/CHANGELOG.md) content
- [ ] https://gama-platform.github.io/download
  - Download links
- [ ] https://gama-platform.github.io/wiki/Home
  - First § talk about 1.8 as the latest
- [ ] https://gama-platform.github.io/wiki/New-Version-Changes
  - Maybe this page is not needed anymore (talk about differences between 1.6 and 1.8 => Already have the _release_ page)
- [ ] https://gama-platform.github.io/wiki/Installation
  - Ref at the 1.8.0
- [ ] https://gama-platform.github.io/wiki/OlderVersions
  - Add 1.8.1 release

**Comment by AlexisDrogoul** [comment]
I think that we can keep it short and straight for announcing 1.8.1 (on the blog, FB, etc.).

Something like: " We are pleased to release version 1.8.1 of the GAMA modelling and simulation platform. It is mainly a bug fix release, with a few minor enhancements. See the changelog here. All the models running on 1.8 should work without changes on 1.8.1. As usual, make a backup of your files before upgrading and report any issues here. "

With the correct insertion of links where they should go.. With that, normally, you have all what is required to make the above changes (with which I completely agree).

**Comment by RoiArthurB** [comment]
I'm starting a branch to change this all (modifications will only be visible in local, Travis compile only the `sources` branch) :)

**Comment by RoiArthurB** [comment]
@AlexisDrogoul Mostl of the work is done. Only stuff remaining is to automatically update the changelog, but I'll need a little bit more time/work and it's not strictly needed for the release. 

So the website is ready to release the GAMA 1.8.1 version and release a blog post about it ! :smile:

**Comment by RoiArthurB** [comment]
Branch merged here too, the website is rebuild and will soon be updated online :D
I'm closing this issue 'cause there's nothing more to do now :)
