### ISSUE TITLE
Broken Link in the page OldVersions

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#87]
**Exact broken link**

On the page, `https://gama-platform.github.io/wiki/OlderVersions`, some of the links toward documentation pdf files  are broken.

**Comment by RoiArthurB** [comment]
I fixed most of the links : the only missing one is the 1.8.1 PDF (which hasn't been generated yet) :)

So if you can create it and upload it in the wiki at that path : `wiki/resources/pdf/` with that file name `docGAMAv1.8.1.pdf` it'll be perfect :smile:

**Comment by RoiArthurB** [comment]
Ping @benoitgaudou ?
