### ISSUE TITLE
Missing definition of message datatype

### ISSUE THREAD

**Issue by LedanDark** [gama-platform/gama-platform.github.io#88]
**Describe the bug**
message datatype does not have definition in the wiki. 
Typing message into the search bar gives only the operator "message". 
Typing "types" into the search bar gives a list of all types, including "message".
Clicking the link to "message" in the above list redirects to https://gama-platform.github.io/wiki/DataTypes#message

However, in the page https://gama-platform.github.io/wiki/DataTypes there is no definition for the type "message".

**To Reproduce**
1. Go to  https://gama-platform.github.io/wiki/DataTypes#message
2. Observer that there is no definition for the message data type

**Expected behavior**
Expectation is that message data type has a definition in this document.
Currently having to dredge through "examples" to find what the contents of this datatype are. 

Expected to see 
''' message
sender : agent that sent this message
contents : contents of this message
etc'''

**Comment by benoitgaudou** [comment]
This has been fixed, while documenting the FIPA skill
