### ISSUE TITLE
Problems with the doc of actions in a skill: 'returns' description missing

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama-platform.github.io#90]
For example: https://gama-platform.github.io/wiki/BuiltInSkills#compute_path
![image](https://user-images.githubusercontent.com/34294427/117565362-f8e44280-b0da-11eb-8f51-6902eadb7630.png)
and the corresponding annotation in Java:
```
@action(
	...
	doc = @doc (
		value = "action to compute a path to a target location according to a given graph",
		returns = "the computed path, return nil if no path can be taken",
		examples = { @example ("do compute_path graph: road_network target: the_node;") }))
```
I spotted a few problems:
* The action description is formatted in a code block, but it should just be normal text
* The return value description does not match
* The example code is missing

I guess the last two might be due to the website not having been updated yet.

**Comment by benoitgaudou** [comment]
Dear Duc,
Thank you  for the  remarks, I will have  a look to solve that.

But first  of all,   @Huynh Quang Nghi 002628 ***@***.***> : On the
page there is the message:
"
BuiltInSkills
Edit <https://github.com/gama-platform/gama/wiki/BuiltInSkills/_edit>New
Page <https://github.com/gama-platform/gama/wiki/_new>
Travis CI edited this page on 12 Aug 2020 · 43 revisions
<https://github.com/gama-platform/gama/wiki/BuiltInSkills/_history>
"
I am wondering whether the documentation is still updated with the new
continuous integration ?

Cheers

Benoit
<https://github.com/gama-platform/gama/wiki/BuiltInSkills#built-in-skills>

**Comment by hqnghi88** [comment]
Dear Benoit, 
I just take a look , there is a break on continuous integration, i just make it works again, you can use "ci docs" to see the changes immediately after the commit.

**Comment by RoiArthurB** [comment]
Added a daily automated workflow dedicated to refreshing generated documentation, you check it here : https://github.com/gama-platform/gama/actions/workflows/github-daily-doc-wiki-refresh.yaml

Let's see tomorrow if it's all fixed :smiley:

**Comment by RoiArthurB** [comment]
@hqnghi88 the command `ci docs` is broken, see gama-platform/gama#3349
