### ISSUE TITLE
Review documentation about Using R

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#93]
When I look at the page: 
https://gama-platform.github.io/wiki/CallingR#configuration-in-gama

I admit that it is not clear what this line referes to:
```
In "Config RScript's path", browse to your "Rscript" file (R language installed in your system).
```

It has been replaced by  
```
Path to JRI library ($R_HOME/ .....) 
```
right ?

**Comment by lesquoyb** [comment]
### **General information to help with the editing of the documentation**
Every wiki page of the documentation can be directly modified at the address : [https://github.com/gama-platform/gama/wiki](https://github.com/gama-platform/gama/wiki) followed by the name of the page and then click on the `edit` button in the top-right hand-corner.
The website will be updated at the next travis build.

For example to update the [https://gama-platform.org/wiki/Home](https://gama-platform.org/wiki/Home) page, we go to [https://github.com/gama-platform/gama/wiki/Home](https://github.com/gama-platform/gama/wiki/Home) and click here :
![image](https://user-images.githubusercontent.com/6374469/159215274-4b086e82-a6e3-4300-b7dd-63bb918b04d0.png)



_So in this case the page to edit would be [https://github.com/gama-platform/gama/wiki/CallingR#configuration-in-gama](https://github.com/gama-platform/gama/wiki/CallingR#configuration-in-gama)_

**Comment by benoitgaudou** [comment]
The page  : https://github.com/gama-platform/gama/wiki/CallingR

has  been totally rewritten.

Need to be completed with Windows and Linux configuration...
