### ISSUE TITLE
The installation page needs to be updated for 1.8.2

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#96]
**Describe the problem**
Go to https://github.com/gama-platform/gama/wiki/Installation : most of the procedures need to be updated for 1.8.2

**Comment by RoiArthurB** [comment]
Done :smiley:

**Comment by RoiArthurB** [comment]
Should add screenshot for step by step instruction
- [ ] Windows @LucasGrjs or @ptaillandier 
- [ ] MacOS @benoitgaudou 
- [ ] Ubuntu @lesquoyb
