### ISSUE TITLE
Change the version of the site when going

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama-platform.github.io#98]
**Describe the bug**
On the website, thee page Download, FAQ ... make the website move back to the 1.8.1 version.

**To Reproduce**
1. Click on the 1.8.1 to move to page allowing you to choose the version of the website. Choose Next.
2. Click on The Download link on  the top  of the page
3. The page moves back to the version 1.8.1.

**Comment by RoiArthurB** [comment]
It's something that we can't fix and is depending on Docusaurus v1 that we're currently using. 
I may be fixed in future website development :)
